# Day15_probability
19-mar-25

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stat

### Calculate probability of continuoues random variable

In [8]:
#E1 Find the probabilty of getting the marks <=680,mean=711,std=29

In [14]:
p_less_680=stat.norm.cdf(680,loc=711,scale=29) # thi sformula gives the zscore(standardised value) for 680
np.round(p_less_680*100,2)
# loc - mean
# scale - std deviation
#14.25 percent of probability of getting marks less than 680

14.25

In [ ]:
#E2 Find out the probabilty of getting the marks >720,mean=711,std=29
# As we can not find the right side area(grater than) of any vaule, first we need to find out less than arean and minus it with 1

In [20]:
p_less_720=stat.norm.cdf(720,loc=711,scale=29)
print(p_less_720)
p_greater_720=1-p_less_720
print(np.round(p_greater_720*100,2))


0.621850627348053
37.81


In [28]:
import scipy
p_less_720=scipy.stats.norm.cdf(720,loc=711,scale=29)
print(p_less_720)
p_greater_720=1-p_less_720
print(np.round(p_greater_720*100,2))

0.621850627348053
37.81


In [ ]:
#E3 Find out the probabilty of getting the between 680<= marks <= 720,mean=711,std=29


In [36]:
probability_between_680_720=p_less_720-p_less_680
print(np.round(probability_between_680_720*100,2))
#p_less_680+probability_between_680_720+p_greater_720 should be equal to 100 as area under the curve is always 100

47.93


In [38]:
p_less_680+probability_between_680_720+p_greater_720 

1.0

In [ ]:
### E2 - find the prob of gertting marks between  680 and720, mean =711,std=29

In [3]:
import pandas as pd
import numpy as np
import scipy.stats as stat

In [ ]:
p_between=

## 15.2 Central limit theorem

# Confidence interval - using z distruition

In [5]:

c_int_z95=stat.norm.interval(0.95,loc=1990,scale=2500/np.sqrt(140))
np.round(c_int_z95)

array([1576., 2404.])

In [3]:
c_int_z90=stat.norm.interval(0.90,loc=1990,scale=2500/np.sqrt(140))# loc - sample mean
np.round(c_int_z90)

array([1642., 2338.])

In [24]:
c_tax_z90=stat.norm.interval(0.90,loc=23.6,scale=7/np.sqrt(100))
np.round(c_tax_z90)

array([22., 25.])

# Confidence interval - using t distruition

In [8]:
c_int_t95=stat.t.interval(0.95,df=139,loc=1990,scale=2833/np.sqrt(140))
np.round(c_int_t95)#df=n-1=140-1=139
# 2833 - population std dev
# loc - 1990 - sample mean

array([1517., 2463.])

In [7]:
c_tax_t90=stat.t.interval(0.90,df=99,loc=23.6,scale=7/np.sqrt(140))
print(c_tax_t90)

(22.617699344997238, 24.582300655002765)


## PPF - is used to find the Z corrresponding to the probability, till now we were finding probability by using Z now itws reverse

In [13]:
stat.norm.ppf(0.05)

-1.6448536269514729

In [16]:
stat.norm.ppf(0.95)

1.6448536269514722