# Day31_Association_rule_practise
16-Apr-25


In [1]:
!pip install mlxtend

   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------------------------------- -------- 1.0/1.4 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 3.3 MB/s eta 0:00:00


In [2]:
from mlxtend import frequent_patterns
from mlxtend.preprocessing import TransactionEncoder

In [3]:
items_list=[['Milk','Onion','Nutmeg','Kidney Beans','Eggs','Yogurt'],
           ['Dill','Onion','Nutmeg','Kidney Beans','Eggs','Yogurt'],
            ['Milk','Apple','Kidney Beans','Eggs'],
            ['Milk','Unicorn','Corn','Kidney Beans','Yogurt'],
            ['Corn','Onion','Onion','Kidney Beans','Ice cream','Eggs']
           ]

In [4]:
type(items_list)

list

In [5]:
items_list

[['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
 ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
 ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

# Step 1 - Convert the transaction into 0,1 by using encoder

In [6]:
enc=TransactionEncoder()
enc.fit_transform(items_list)

array([[False, False, False,  True, False,  True,  True,  True,  True,
        False,  True],
       [False, False,  True,  True, False,  True, False,  True,  True,
        False,  True],
       [ True, False, False,  True, False,  True,  True, False, False,
        False, False],
       [False,  True, False, False, False,  True,  True, False, False,
         True,  True],
       [False,  True, False,  True,  True,  True, False, False,  True,
        False, False]])

In [7]:
# lets convert the above array output in dataframe for further use

In [8]:
import pandas as pd
enc_encoded_df=pd.DataFrame(enc.fit_transform(items_list),columns=enc.columns_)

In [9]:
enc_encoded_df.head()

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False


# Step 2 - find out frequent itemset using apriori algorithm

In [45]:
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
# To find out the frequent itemsest we need to mention the thereshold(min_support)

In [56]:
frequent_items=apriori(enc_encoded_df,min_support=0.6,use_colnames=True)
frequent_items

,support,itemsets
0,0.8,(Eggs)
1,1.0,(Kidney Beans)
2,0.6,(Milk)
3,0.6,(Onion)
4,0.6,(Yogurt)
5,0.8,"(Eggs, Kidney Beans)"
6,0.6,"(Eggs, Onion)"
7,0.6,"(Kidney Beans, Milk)"
8,0.6,"(Kidney Beans, Onion)"
9,0.6,"(Yogurt, Kidney Beans)"


# Step 3 - Find association rule

In [61]:
assoc_rule=association_rules(frequent_items,min_threshold=1.0,num_itemsets=5)
# num_items - no of transactions
# confidance - min_threshold=1.0
# num_itemsets=5- no of transactions
assoc_rule

C:\Users\Pandhari\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)


,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.0,1.00,1.0,0.00,inf,0.0,0.80,0.0,0.900
1,(Onion),(Eggs),0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875
2,(Milk),(Kidney Beans),0.6,1.0,0.6,1.0,1.00,1.0,0.00,inf,0.0,0.60,0.0,0.800
3,(Onion),(Kidney Beans),0.6,1.0,0.6,1.0,1.00,1.0,0.00,inf,0.0,0.60,0.0,0.800
4,(Yogurt),(Kidney Beans),0.6,1.0,0.6,1.0,1.00,1.0,0.00,inf,0.0,0.60,0.0,0.800
5,"(Eggs, Onion)",(Kidney Beans),0.6,1.0,0.6,1.0,1.00,1.0,0.00,inf,0.0,0.60,0.0,0.800
6,"(Kidney Beans, Onion)",(Eggs),0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875
7,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875


In [67]:
assoc_rule[assoc_rule['lift']>1]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1,(Onion),(Eggs),0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875
6,"(Kidney Beans, Onion)",(Eggs),0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875
7,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875


# 31.2) Model validation

## 31.2) K-fold validation

In [10]:
import pandas as pd

In [12]:
data=pd.read_csv('pima_indians_diabetes.csv')

In [14]:
data.head()

,preg,plas,pres,skin,test,mass,pedi,age,class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [16]:
data.shape

(768, 9)

In [22]:
x=data.drop('class', axis=1)
y=data['class']

In [24]:
x.head()

,preg,plas,pres,skin,test,mass,pedi,age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33


In [26]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: class, dtype: int64

- First lets try the model validation by using train test split

#### a. Train test split

In [32]:
from sklearn.model_selection import train_test_split

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [40]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((614, 8), (154, 8), (614,), (154,))

In [ ]:
# while evaluating any model use all theree methods. And compare the accuracy of alll three and decide models accuracy
1) confusion matrix, classification model,MSE,RMSE
2) K-fold
3) Leave one out

#### a.1) Build the model

In [42]:
from sklearn.linear_model import LogisticRegression

In [46]:
clf=LogisticRegression(max_iter=400)

In [50]:
clf.fit(x_train,y_train)

LogisticRegression(max_iter=400)

#### a.2) predict - train data

In [58]:
yhat_train=clf.predict(x_train)

In [62]:
yhat_train

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

#### a.3) Evaluate the model - train data 

In [66]:
from sklearn.metrics import confusion_matrix,classification_report

In [68]:
conf_mat=confusion_matrix(y_train,yhat_train)
print(conf_mat)
print(classification_report(y_train,yhat_train))

[[353  48]
 [ 93 120]]
              precision    recall  f1-score   support

           0       0.79      0.88      0.83       401
           1       0.71      0.56      0.63       213

    accuracy                           0.77       614
   macro avg       0.75      0.72      0.73       614
weighted avg       0.76      0.77      0.76       614



- accuracy - 0.77%

#### a.3) predict - test data 

In [75]:
yhat_test=clf.predict(x_test)

#### a.4) Evaluate the model - test data 

In [82]:
conf_mat_test=confusion_matrix(y_test,yhat_test)
print(conf_mat_test)
print(classification_report(y_test,yhat_test))

[[78 21]
 [18 37]]
              precision    recall  f1-score   support

           0       0.81      0.79      0.80        99
           1       0.64      0.67      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154



#### b. K-fold validation

In [85]:
from sklearn.model_selection import KFold,cross_val_score

In [87]:
kfold=KFold(n_splits=10)

In [93]:
cvals=cross_val_score(clf,x,y,cv=kfold,scoring='accuracy')
cvals

array([0.68831169, 0.81818182, 0.76623377, 0.68831169, 0.77922078,
       0.79220779, 0.84415584, 0.83116883, 0.75      , 0.80263158])

- So it has given 10 accusracies based on splits. So we can consider avg of these 10 ouput would be our model accuracy

In [96]:
cvals.mean()

0.7760423786739576

- Model has 77% accuracy

#### c.leave one out

In [107]:
from sklearn.model_selection import LeaveOneOut

In [109]:
loocv=LeaveOneOut()

In [111]:
lvals=cross_val_score(clf,x,y,cv=loocv,scoring='accuracy')

In [112]:
lvals

array([1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 1.

In [42]:
import numpy as np
np.unique(lvals)

array([0., 1.])

In [49]:
count=pd.DataFrame(lvals)
count.value_counts() # This model will give the same no of accuracies what record has

0  
1.0    596
0.0    172
Name: count, dtype: int64

In [115]:
lvals.mean() - accuracy

0.7760416666666666