# Day44_Neural_ntwrk_Mnist
Mnist dataset - it is a dataset in which it has 60k images of handwritten numbers and we are going to predict what each image represent it(0,1,2,3,4,5,6,7,8,9).

In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Input # Flatten - Converts multi-dimensional input (like a 2D image) into a 1D vector.
# ex- if we have inpput matrix as 28*28 then flatten will convert it into 1d array of 784.
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt
import numpy as np

In [6]:
# Load the dataset
(x_train,y_train_orig),(x_test,y_test_orig)=mnist.load_data()

In [10]:
x_train.shape,y_train_orig.shape,x_test.shape,y_test_orig.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [12]:
type(x_train)

numpy.ndarray

In [14]:
#print(x_train)

In [16]:
import pandas as pd
#df=pd.DataFrame(x_train)

In [18]:
#print(x_test)

In [20]:
print(y_train_orig)

[5 0 4 ... 5 6 8]


In [22]:
# Normalize the pixel values to [0,1]
x_train=x_train/255
x_test=x_test/255

In [24]:
#print(x_test)

In [26]:
# convert labels to one hot encoder
y_train=to_categorical(y_train_orig,10)# 10 are no of classes as we need to find 0 to 9 values.
y_test=to_categorical(y_test_orig,10)

In [28]:
print(y_train_orig)

[5 0 4 ... 5 6 8]


In [30]:
#print(y_train)

In [32]:
print(y_test_orig)

[7 2 1 ... 4 5 6]


In [34]:
print(y_test)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [36]:
# Steps with respect to model  
# 1 Build the model
# 2 compile the model
# 3 fit the model
# 4 evaluate the model

In [38]:
# Build the model
model=Sequential(
                [Flatten(input_shape=(28,28)),# flatten 28*28 image into 784
                 Dense(128,activation='relu'),
                 Dense(64,activation='relu'),
                 Dense(10,activation='softmax')
                 ]
                 )

C:\Users\Pandhari\anaconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [40]:
# Train the model - It configures the model for training by setting three key things:optimizer,loss,metrics
model.compile(optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'])

In [42]:
# Train the model
history=model.fit(x_train,
    y_train,
    batch_size=32,
    epochs=10,
    validation_split=0.2)

Epoch 1/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8571 - loss: 0.4825 - val_accuracy: 0.9568 - val_loss: 0.1437
Epoch 2/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9642 - loss: 0.1189 - val_accuracy: 0.9658 - val_loss: 0.1074
Epoch 3/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9767 - loss: 0.0744 - val_accuracy: 0.9707 - val_loss: 0.0976
Epoch 4/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9829 - loss: 0.0533 - val_accuracy: 0.9743 - val_loss: 0.0876
Epoch 5/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9876 - loss: 0.0398 - val_accuracy: 0.9744 - val_loss: 0.0913
Epoch 6/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9903 - loss: 0.0304 - val_accuracy: 0.9745 - val_loss: 0.0907
Epoch 7/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9921 - loss: 0.0259 - val_accuracy: 0.9750 - val_loss: 0.0922
Epoch 8/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9938 - loss: 0.0207 - 

In [44]:
x_test.shape

(10000, 28, 28)

In [46]:
# Evaluate the model on test data
test_loss, test_accuracy=model.evaluate(x_test,y_test)
print(f"\nTest Accuracy: {test_accuracy:.4f}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9726 - loss: 0.1082

Test Accuracy: 0.9753


In [48]:
# Optional: This saves the model so it can be loaded in a new script for prediction.
model.save("mnist_ann_model.h5")